%% Multi-offset centered-signal photon, residual-Kerr, and design-gap audit.

clear;clc;scriptDir=fileparts(mfilename('fullpath'));
loadedLinewidthHz=8e6;kappaNormalized=.120;
frequencyUnitRad=2*pi*loadedLinewidthHz/kappaNormalized;
kappaExternal=.5*2*pi*loadedLinewidthHz;etaDetection=.50;
dtPhysical=.0125/frequencyUnitRad;virtualIndices=[11 20 29 37 46 55];
integrationTime=min(diff(virtualIndices))*dtPhysical;
referencePowerPerRing=0.224e-9;targetEffectivePhotons=1e4;
Jvalues=[0 .65];conditionNames=["J=0";"J=0.65"];

hbar=1.054571817e-34;c0=299792458;lambda0=1550e-9;
omega0=2*pi*c0/lambda0;nIndex=1.977;n2=2.3e-19;
modeVolume=1000e-18;
kerrRadPerPhoton=hbar*omega0^2*c0*n2/(nIndex^2*modeVolume);
kerrHzPerPhoton=kerrRadPerPhoton/(2*pi);kappaRad=2*pi*loadedLinewidthHz;

nOffsets=10;nConditions=2;nRows=nOffsets*nConditions;
condition=repmat(conditionNames,nOffsets,1);
J=repmat(Jvalues(:),nOffsets,1);
offset=repelem((101:110).',nConditions,1);
meanOccupancy=nan(nRows,1);carrierEffectivePhotons=meanOccupancy;
medianRawEffectivePhotons=meanOccupancy;minimumRawEffectivePhotons=meanOccupancy;
medianPcaEffectivePhotons=meanOccupancy;minimumPcaEffectivePhotons=meanOccupancy;
dynamicToCarrierRatio=meanOccupancy;requiredPowerMedianPca_W=meanOccupancy;
requiredPowerMinimumPca_W=meanOccupancy;kerrShiftOverKappa=meanOccupancy;
kerrBoundaryPower_W=meanOccupancy;kerrBoundaryEffectivePhotons=meanOccupancy;
requiredSignalKerrImprovement=meanOccupancy;

for row=1:nRows
    conditionIndex=mod(row-1,nConditions)+1;
    tag=sprintf('DynamicPhotonAudit_C%02d_Offset%04d_20260812', ...
        conditionIndex,offset(row));
    file=fullfile(scriptDir, ...
        ['Fig3_KerrReservoir_NARMA10_Reproducible_' tag '_summary.mat']);
    assert(isfile(file),'Missing trajectory %s.',file);
    S=load(file,'Xvirt','cfg','P','pcaInfo');
    assert(isequal(size(S.Xvirt),[22000 144]) && S.P.N==12 && ...
        S.cfg.numReservoirs==1 && abs(S.P.J0-J(row))<1e-14 && ...
        S.cfg.seedOffset==offset(row));
    train=S.cfg.idxTrain(:);X=S.Xvirt(train,:);
    rawVariance=var(X,1,1);
    rawEffective=.5*etaDetection*kappaExternal*integrationTime*rawVariance;
    medianRawEffectivePhotons(row)=median(rawEffective);
    minimumRawEffectivePhotons(row)=min(rawEffective);

    mu=S.pcaInfo.mu;sig=S.pcaInfo.sig;V=S.pcaInfo.Vpc;
    Z=(X-mu)./sig*V;
    pcSignalVariance=var(Z,1,1);
    rawNoiseToPc=sum((V./sig.').^2,1);
    pcEffective=.5*etaDetection*kappaExternal*integrationTime* ...
        pcSignalVariance./rawNoiseToPc;
    medianPcaEffectivePhotons(row)=median(pcEffective);
    minimumPcaEffectivePhotons(row)=min(pcEffective);

    nModes=S.P.N;nVirtual=numel(S.cfg.virtualNodeIdx);occupation=[];
    for v=1:nVirtual
        cols=(v-1)*2*nModes+(1:2*nModes);
        block=X(:,cols);
        occupation=[occupation; ...
            block(:,1:nModes).^2+block(:,nModes+(1:nModes)).^2]; %#ok<AGROW>
    end
    meanOccupancy(row)=mean(occupation,'all');
    carrierEffectivePhotons(row)=.5*etaDetection*kappaExternal* ...
        integrationTime*meanOccupancy(row);
    dynamicToCarrierRatio(row)= ...
        medianPcaEffectivePhotons(row)/carrierEffectivePhotons(row);
    requiredPowerMedianPca_W(row)=referencePowerPerRing* ...
        targetEffectivePhotons/medianPcaEffectivePhotons(row);
    requiredPowerMinimumPca_W(row)=referencePowerPerRing* ...
        targetEffectivePhotons/minimumPcaEffectivePhotons(row);
    scaledOccupancy=meanOccupancy(row)* ...
        requiredPowerMedianPca_W(row)/referencePowerPerRing;
    kerrShiftOverKappa(row)=kerrRadPerPhoton*scaledOccupancy/kappaRad;
    kerrBoundaryPower_W(row)=requiredPowerMedianPca_W(row)* ...
        .1/kerrShiftOverKappa(row);
    kerrBoundaryEffectivePhotons(row)=targetEffectivePhotons* ...
        .1/kerrShiftOverKappa(row);
    requiredSignalKerrImprovement(row)= ...
        targetEffectivePhotons/kerrBoundaryEffectivePhotons(row);
end

raw=table(condition,J,offset,meanOccupancy,carrierEffectivePhotons, ...
    medianRawEffectivePhotons,minimumRawEffectivePhotons, ...
    medianPcaEffectivePhotons,minimumPcaEffectivePhotons, ...
    dynamicToCarrierRatio,requiredPowerMedianPca_W, ...
    requiredPowerMinimumPca_W,kerrShiftOverKappa,kerrBoundaryPower_W, ...
    kerrBoundaryEffectivePhotons,requiredSignalKerrImprovement);
writetable(raw,fullfile(scriptDir, ...
    'DynamicPhotonKerrMultiOffset_Raw_20260813.csv'));

variables={'medianPcaEffectivePhotons','requiredPowerMedianPca_W', ...
    'kerrShiftOverKappa','kerrBoundaryPower_W', ...
    'kerrBoundaryEffectivePhotons','requiredSignalKerrImprovement'};
summary=table(conditionNames,Jvalues(:),'VariableNames',{'condition','J'});
for v=1:numel(variables)
    values=raw.(variables{v});
    med=nan(2,1);lo=med;hi=med;
    for c=1:2
        selected=values(raw.J==Jvalues(c));
        med(c)=median(selected);lo(c)=prctile(selected,2.5);
        hi(c)=prctile(selected,97.5);
    end
    summary.([variables{v} '_median'])=med;
    summary.([variables{v} '_p025'])=lo;
    summary.([variables{v} '_p975'])=hi;
end
writetable(summary,fullfile(scriptDir, ...
    'DynamicPhotonKerrMultiOffset_Summary_20260813.csv'));

fid=fopen(fullfile(scriptDir, ...
    'DynamicPhotonKerrMultiOffset_Audit_20260813.md'),'w');assert(fid>=0);
cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'# Multi-offset photon and residual-Kerr audit\n\n');
fprintf(fid,['Ten prospectively defined selection offsets are evaluated per ' ...
    'coupling condition. Intervals are empirical 2.5--97.5 percentiles across ' ...
    'offsets and are not fabrication-tolerance intervals.\n\n']);
fprintf(fid,'- Reference input: `%.3f nW/ring`.\n',referencePowerPerRing*1e9);
fprintf(fid,'- Target precision scale: `%.0e` effective photons.\n',targetEffectivePhotons);
fprintf(fid,'- Kerr boundary: `|K| nbar/kappa = 0.1`.\n');
fprintf(fid,'- Representative `K/(2 pi) = %.3g Hz/photon`.\n\n',kerrHzPerPhoton);
for c=1:2
    fprintf(fid,['- `%s`: precision power median `%.4g W/ring` ' ...
        '[`%.4g`, `%.4g`]; Kerr-boundary power median `%.4g mW/ring` ' ...
        '[`%.4g`, `%.4g`]; boundary effective photons median `%.4g` ' ...
        '[`%.4g`, `%.4g`]; required signal/Kerr improvement median `%.4g` ' ...
        '[`%.4g`, `%.4g`].\n'],conditionNames(c), ...
        summary.requiredPowerMedianPca_W_median(c), ...
        summary.requiredPowerMedianPca_W_p025(c), ...
        summary.requiredPowerMedianPca_W_p975(c), ...
        1e3*summary.kerrBoundaryPower_W_median(c), ...
        1e3*summary.kerrBoundaryPower_W_p025(c), ...
        1e3*summary.kerrBoundaryPower_W_p975(c), ...
        summary.kerrBoundaryEffectivePhotons_median(c), ...
        summary.kerrBoundaryEffectivePhotons_p025(c), ...
        summary.kerrBoundaryEffectivePhotons_p975(c), ...
        summary.requiredSignalKerrImprovement_median(c), ...
        summary.requiredSignalKerrImprovement_p025(c), ...
        summary.requiredSignalKerrImprovement_p975(c));
end
fprintf(['DYNAMIC_PHOTON_MULTIOFFSET_PASS rows=%d ' ...
    'gap=[%.4g %.4g]\n'],height(raw), ...
    summary.requiredSignalKerrImprovement_median);
